version: '3'

volumes:
  leaderboarddbvolume:
  redisvolume:

services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    deploy:
      replicas: 1
    environment:
      POSTGRES_PASSWORD: leaderboard
      POSTGRES_USER: leaderboard
      POSTGRES_DB: leaderboard
    volumes:
      - leaderboarddbvolume:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redisvolume:/data
    ports:
      - 6379:6379
  web:
    # image: leaderboard
    build: .
    ports:
      - 8000:8000
    depends_on: 
      - redis
      - db
    environment: 
      REDIS_HOST: 'redis'
      DATABASE_NAME: 'leaderboard'
      DATABASE_USER: 'leaderboard'
      DATABASE_PASSWORD: 'leaderboard'
      DATABASE_PORT: 5432
      DATABASE_HOST: 'db'