# Generated by Django 3.0.7 on 2020-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='tr', max_length=8),
            preserve_default=False,
        ),
    ]
